language: ruby
rvm: 2.2.0
sudo: false
cache:
  apt: true
addons:
  apt_packages:
  - bc
script: bundle exec chirp scripts
after_script: bundle exec chirp pushback &>/dev/null
after_failure: bundle exec chirp dumplogs
notifications:
  webhooks:
    urls:
    - 'https://chirp-tracker-production.herokuapp.com/travis'
    on_success: always
    on_failure: never
