language: ruby
sudo: false
rvm: 2.5.1
env:
  global:
  - CHIRP_SUMMARY_OUTPUT="${TRAVIS_BUILD_DIR}/chirp.json"
  - SITE=org
addons: { apt: { packages: [bc] } }
linux_shared: &linux_shared
  os: linux
  addons: { apt: { packages: [bc] } }
matrix:
  include:
  - sudo: false
    dist: trusty
    env: QUEUE=ec2 DIST=trusty
    <<: *linux_shared
  - sudo: required
    dist: trusty
    env: QUEUE=gce DIST=trusty
    <<: *linux_shared
  - sudo: required
    dist: xenial
    group: edge
    env: QUEUE=gce DIST=xenial
    <<: *linux_shared
  - os: osx
    osx_image: xcode8.3
    env: QUEUE=macos DIST=xcode8.3
before_install:
- gem update --system
- gem install bundler
script: bundle exec chirp scripts
after_script: bundle exec chirp sendstats 2>/dev/null
after_failure: bundle exec chirp dumplogs
