language: ruby

sudo: false

rvm: 2.2.3

addons: { apt: { packages: [bc] } }

linux_shared: &linux_shared
  os: linux
  addons: { apt: { packages: [bc] } }

matrix:
  include:
  - sudo: required
    dist: trusty
    env: QUEUE=gce DIST=trusty
    <<: *linux_shared
  - sudo: required
    dist: precise
    env: QUEUE=gce DIST=precise
    <<: *linux_shared
  - sudo: false
    dist: precise
    env: QUEUE=docker DIST=precise
    <<: *linux_shared
  - sudo: false
    dist: trusty
    group: beta
    env: QUEUE=ec2 DIST=trusty
    <<: *linux_shared
  - os: osx
    rvm: default
    env: QUEUE=macstadium6 IMAGE=default
  - os: osx
    osx_image: xcode7
    rvm: default
    env: QUEUE=macstadium6 IMAGE=xcode7

script: bundle exec chirp scripts

after_script: bundle exec chirp sendstats 2>/dev/null

after_failure: bundle exec chirp dumplogs

notifications:
  webhooks:
    urls:
    - 'https://chirp-tracker-production.herokuapp.com/travis'
    on_success: always
    on_failure: never
