language: ruby
rvm: 2.5.0
os: osx
osx_image: xcode9.3-lite
before_install: gem update --system
script: bundle exec chirp scripts
env:
  matrix:
  - I=00
  - I=01
  - I=02
  - I=03
  - I=04
  - I=05
  - I=06
  - I=07
  - I=08
  - I=09
  - I=10
  - I=11
  - I=12
  - I=13
  - I=14
  - I=15
  - I=16
  - I=17
  - I=18
  - I=19
